language: go
go:
- master
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get .
script:
- go test -v -covermode=count -coverprofile=coverage.out
- echo $COVERALLS_TOKEN
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
env:
  global:
    secure: x9V+In1hnUAB4jwuud2QJ/p6qkreZl3jLGQ09uZmdOPuDQD42B6Q6tD9jWXz3XPqCOHVEK2NbsOE1j8wi21GsY/v6/c+0Id+TuBOVxdJ1U3rVZRGWraRg/qxoujwbdn4V6ANUJfMlSmAKwgTd9/7oTAEkNj6gooUKmOzXHVhs2fMpQ5gn5C9pk/r9w3Gu/DFOV9ssvXRfISaeIxm+9KLGxo6D0R4bV/auyK3OwcSEzVhiozoa/rioOFseUZK56ZXe67aCd8e+peAUx+KvExbWj+Zi/Dc3VrJIyua6qv5m/L6AK3sYsYdRDrf4jTbGdYpX9eZp/OpB46i1yWSRL61B7MwGR4nmNT5CtSmpBgwdFFbDuXyySwJZNRqi1gUR2bhahSRKTMLXhZiEWxagnxfT4Y6EmBMd1N/3ATmY6qWAhCZXZAUkZHDy/ZdpWRJVhDzAuLY9rxG/h023FuLwp7Mf6bM4UIK/SEbnLexKkG3nLJONxs3SHIGRoqr3V5TJAUvUj6BqxcHvRBzpNRpBY4UOXDpCPqm3Lkso4vBktNHKpAqSwT3g7eE9a2U+1birJtDn1B3FHhGKuiUAA1kwma7A8Ng38xJkfcj6nZzjtHjWHAGm6a18bo+i1tRCa+d4417VCKteysMaIS9JnsK0p3fj2IFHWIBcflhR8Oj6OplIQA=
